"""initial schema

Revision ID: 1740ccf419d5
Revises:
Create Date: 2026-06-20 14:50:56.464549

Hand-written rather than autogenerated: there is no existing database to
diff against yet (this is the first migration), so the upgrade/downgrade
bodies are written directly from app/db/models.py.

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1740ccf419d5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "clients",
        sa.Column("id", postgresql.UUID(as_uuid=False), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("profile_name", sa.Text(), nullable=False, server_default=""),
        sa.Column("profile_current_role", sa.Text(), nullable=False, server_default=""),
        sa.Column("profile_location", sa.Text(), nullable=False, server_default=""),
        sa.Column("profile_target_geography", sa.Text(), nullable=False, server_default=""),
        sa.Column("profile_desired_next_move", sa.Text(), nullable=False, server_default=""),
        sa.Column("profile_timeframe", sa.Text(), nullable=False, server_default=""),
        sa.Column("profile_roles_wanted", sa.Text(), nullable=False, server_default=""),
        sa.Column("profile_roles_not_wanted", sa.Text(), nullable=False, server_default=""),
        sa.Column("profile_constraints", sa.Text(), nullable=False, server_default=""),
        sa.Column("profile_relationship_assets", sa.Text(), nullable=False, server_default=""),
        sa.Column("profile_advisor_notes", sa.Text(), nullable=False, server_default=""),
        sa.Column("profile_cv_text", sa.Text(), nullable=False, server_default=""),
        sa.Column("cv_intelligence", postgresql.JSONB(), nullable=True),
        sa.Column("cv_intelligence_raw", sa.Text(), nullable=True),
        sa.Column("cv_intelligence_generated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("positioning", postgresql.JSONB(), nullable=True),
        sa.Column("positioning_raw", sa.Text(), nullable=True),
        sa.Column("positioning_generated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("market_radar", postgresql.JSONB(), nullable=True),
        sa.Column("market_radar_raw", sa.Text(), nullable=True),
        sa.Column("market_radar_generated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("market_radar_is_complete", sa.Boolean(), nullable=True),
        sa.Column("market_radar_scan_warning", sa.Text(), nullable=True),
        sa.Column("advisor_brief", postgresql.JSONB(), nullable=True),
        sa.Column("advisor_brief_raw", sa.Text(), nullable=True),
        sa.Column("advisor_brief_generated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("advisor_brief_is_edited", sa.Boolean(), nullable=True),
        sa.Column("advisor_brief_edited_at", sa.DateTime(timezone=True), nullable=True),
    )

    op.create_table(
        "opportunities",
        sa.Column("id", postgresql.UUID(as_uuid=False), primary_key=True),
        sa.Column(
            "client_id",
            postgresql.UUID(as_uuid=False),
            sa.ForeignKey("clients.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("title", sa.Text(), nullable=False, server_default=""),
        sa.Column("company", sa.Text(), nullable=False, server_default=""),
        sa.Column("pathway", sa.Text(), nullable=False, server_default=""),
        sa.Column("source_type", sa.Text(), nullable=False, server_default=""),
        sa.Column("source_section", sa.Text(), nullable=False, server_default=""),
        sa.Column("confidence", sa.Text(), nullable=False, server_default=""),
        sa.Column("priority", sa.Text(), nullable=False, server_default="Medium"),
        sa.Column("status", sa.Text(), nullable=False, server_default="Monitor"),
        sa.Column("fit_rationale", sa.Text(), nullable=False, server_default=""),
        sa.Column("evidence", sa.Text(), nullable=False, server_default=""),
        sa.Column("relationship_route", sa.Text(), nullable=False, server_default=""),
        sa.Column("next_action", sa.Text(), nullable=False, server_default=""),
        sa.Column("advisor_note", sa.Text(), nullable=False, server_default=""),
        sa.Column("sources", postgresql.JSONB(), nullable=False, server_default="[]"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_opportunities_client_id", "opportunities", ["client_id"])

    op.create_table(
        "target_contacts",
        sa.Column("id", postgresql.UUID(as_uuid=False), primary_key=True),
        sa.Column(
            "client_id",
            postgresql.UUID(as_uuid=False),
            sa.ForeignKey("clients.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "related_opportunity_id",
            postgresql.UUID(as_uuid=False),
            sa.ForeignKey("opportunities.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("name", sa.Text(), nullable=False, server_default=""),
        sa.Column("title", sa.Text(), nullable=False, server_default=""),
        sa.Column("company", sa.Text(), nullable=False, server_default=""),
        sa.Column("linkedin_url", sa.Text(), nullable=False, server_default=""),
        sa.Column("source_url", sa.Text(), nullable=False, server_default=""),
        sa.Column("why_relevant", sa.Text(), nullable=False, server_default=""),
        sa.Column("suggested_angle", sa.Text(), nullable=False, server_default=""),
        sa.Column("confidence", sa.Text(), nullable=False, server_default="Medium"),
        sa.Column("status", sa.Text(), nullable=False, server_default="Not contacted"),
        sa.Column("notes", sa.Text(), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_target_contacts_client_id", "target_contacts", ["client_id"])
    op.create_index(
        "ix_target_contacts_related_opportunity_id",
        "target_contacts",
        ["related_opportunity_id"],
    )

    op.create_table(
        "session_notes",
        sa.Column("id", postgresql.UUID(as_uuid=False), primary_key=True),
        sa.Column(
            "client_id",
            postgresql.UUID(as_uuid=False),
            sa.ForeignKey("clients.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("date", sa.Text(), nullable=False, server_default=""),
        sa.Column("title", sa.Text(), nullable=False, server_default=""),
        sa.Column("notes", sa.Text(), nullable=False, server_default=""),
        sa.Column("advisor_only", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_session_notes_client_id", "session_notes", ["client_id"])

    op.create_table(
        "action_items",
        sa.Column("id", postgresql.UUID(as_uuid=False), primary_key=True),
        sa.Column(
            "client_id",
            postgresql.UUID(as_uuid=False),
            sa.ForeignKey("clients.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "related_opportunity_id",
            postgresql.UUID(as_uuid=False),
            sa.ForeignKey("opportunities.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("action", sa.Text(), nullable=False, server_default=""),
        sa.Column("owner", sa.Text(), nullable=False, server_default="Advisor"),
        sa.Column("due_date", sa.Text(), nullable=False, server_default=""),
        sa.Column("status", sa.Text(), nullable=False, server_default="To do"),
        sa.Column("advisor_note", sa.Text(), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_action_items_client_id", "action_items", ["client_id"])
    op.create_index(
        "ix_action_items_related_opportunity_id", "action_items", ["related_opportunity_id"]
    )


def downgrade() -> None:
    op.drop_table("action_items")
    op.drop_table("session_notes")
    op.drop_table("target_contacts")
    op.drop_table("opportunities")
    op.drop_table("clients")
